name: Testing

on:
  # Only run when this repo changes from private to public.
  # Already public = never
  public
# - push
# - pull_request

jobs:
  build:
    name: Testing Job
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Test
      run: make test
